### PR TITLE
MiniMap Improved

### PR DESCRIPTION
**Pull request by SaharNikkhah**

### CODE REVIEW

**Comment by heostar** [comment]
Hey Sahar I can still see the indicators on top of the characters. Is this fixed on your end ?

**Comment by SaharNikkhah** [comment]
Hey Tae!
Yes! I dont see them on the main camera, only on the mini map! Do you see them on main?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by heostar** [comment]
Yeap I still see them on the main hmm

**Comment by SaharNikkhah** [comment]
Let me check again

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SaharNikkhah** [comment]
Ok! Can you please  try again?
So basically on the main camera for culling mask , minimap layer should be unchecked! I tried it again and I dont see them on the main and commited again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by heostar** [comment]
Thanks Sahar, it's looking good now.

**Review by heostar — APPROVED** [review]

**Comment by SaharNikkhah** [comment]
Tae! Sorry can you approve again , I tried the main after you merged and saw that the position was not right.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
